# Generated by Django 5.2.1 on 2025-05-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.CharField(default='Sin características', max_length=300),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='productos/default.jpg', upload_to='productos/'),
        ),
    ]
